// Generates the Advanced section of mykneescore.com from exported kneescore-research data.
// Usage: node tools/advanced/build.mjs scores.json   (normally called by build.sh)
//
// Writes:
//   advanced/assets/scores-data.js   score metadata + exact question sets
//   advanced/index.html              hub page
//   advanced/<slug>.html             one page per score
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SITE = path.resolve(HERE, "../..");
const OUT = path.join(SITE, "advanced");

// Held back until licence permission is in place
const EXCLUDED = {
  oks: "Oxford Knee Score",
  womac: "WOMAC",
};

// Scores with their own dedicated calculator on the research site (Tools page)
const DEDICATED = { sk11: "sk11", pk7: "pk7" };

// Friendlier file names where the research id differs from the public name
const SLUGS = { ks6: "ks5" };

// Our own instruments, shown in their own group on the hub
const OWN = new Set(["sk11", "pk7", "ks6"]);

const KEEP = [
  "id", "name", "fullName", "acronym", "category", "questions", "completionTime",
  "subscales", "description", "whatItMeasures", "whoItsFor", "typicalUse",
  "strengths", "limitations", "validationLevel", "mcid", "scoringRange",
  "scoringDirection", "scoringInterpretation", "licenseType", "licenseDetails",
  "citation", "pubmedId", "doi", "questionSet",
];

const all = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
const scores = all
  .filter(s => !EXCLUDED[s.id])
  .map(s => {
    const o = {};
    for (const k of KEEP) if (s[k] !== undefined) o[k] = s[k];
    o.slug = SLUGS[s.id] || s.id;
    o.mode = DEDICATED[s.id] || "quick";
    o.own = OWN.has(s.id);
    return o;
  });

for (const s of scores) {
  if (s.mode === "quick" && (!s.questionSet || s.questionSet.length === 0)) {
    throw new Error(`No questions for ${s.name}`);
  }
}

const esc = v => String(v ?? "")
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const commit = process.env.SOURCE_COMMIT || "unknown";

// ---------- data file ----------
fs.mkdirSync(path.join(OUT, "assets"), { recursive: true });
const data = {};
for (const s of scores) data[s.slug] = s;
fs.writeFileSync(
  path.join(OUT, "assets", "scores-data.js"),
  `/* Generated by tools/advanced/build.mjs from SportsHealing/kneescore-research@${commit}. Do not edit by hand. */\n` +
  `window.MKS_SCORES = ${JSON.stringify(data)};\n`
);

// ---------- shared chrome ----------
function head(title, description) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=Hanken+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/advanced.css">
</head>`;
}

function header(current) {
  return `<header>
  <div class="wrap nav">
    <a class="wordmark" href="../index.html">My<span>Knee</span>Score</a>
    <nav aria-label="Main">
      <ul>
        <li><a href="../index.html#how">How it works</a></li>
        <li><a href="../index.html#meaning">Your score</a></li>
        <li><a href="../anatomy.html">Knee anatomy</a></li>
        <li><a href="index.html"${current ? ' aria-current="page"' : ""}>Advanced scores</a></li>
        <li><a class="start-link" href="../index.html#quiz">Start the test</a></li>
      </ul>
    </nav>
  </div>
</header>`;
}

const disclaimer = `<div class="disclaimer">
  <div class="wrap">
    <strong>Important.</strong> These questionnaires are provided for education and self-tracking. A score is not a diagnosis and does not replace advice from a doctor or physiotherapist. Seek urgent care for a knee that is hot, red and swollen, follows a significant injury, or will not bear weight.
  </div>
</div>`;

const footer = `<footer>
  <div class="wrap foot">
    <p>&copy; 2026 mykneescore.com</p>
    <p><a href="../index.html#quiz">Take the test</a> &middot; <a href="index.html">Advanced scores</a> &middot; <a href="#top">Back to top</a></p>
  </div>
</footer>`;

const unvalidated = s => /Unvalidated|Awaiting/.test(s.validationLevel);

function rangeText(s) {
  const dir = s.scoringDirection === "higher_better" ? "higher is better" : "lower is better";
  return `${s.scoringRange.min} to ${s.scoringRange.max}, ${dir}`;
}

// ---------- hub ----------
function card(s) {
  const n = s.mode === "quick" ? s.questionSet.length : s.questions;
  return `<a class="score-card" href="${esc(s.slug)}.html" data-cat="${esc(s.category)}">
          <span class="sc-acronym">${esc(s.acronym)}</span>
          <span class="sc-name">${esc(s.fullName)}</span>
          <span class="sc-meta">${n} question${n === 1 ? "" : "s"} &middot; ${esc(s.completionTime)}</span>
          <span class="sc-tags"><span class="tag">${esc(s.category)}</span><span class="tag${unvalidated(s) ? " tag-warn" : ""}">${esc(s.validationLevel)}</span></span>
        </a>`;
}

const published = scores.filter(s => !s.own);
const own = scores.filter(s => s.own);
const cats = [...new Set(published.map(s => s.category))];

const hub = `${head("Advanced knee scores | My Knee Score", "Clinically used knee questionnaires including KOOS, IKDC, Lysholm, Kujala and more. Answer online and get your score instantly.")}
<body>
${header(true)}
<main id="top">
  <section class="hero hero-slim">
    <div class="wrap">
      <p class="eyebrow">Advanced scores</p>
      <h1>The questionnaires <em>clinicians use.</em></h1>
      <p class="lede">These are the knee scores used by surgeons, physiotherapists and researchers. Each one asks about a specific kind of knee problem. Pick the one that fits you, answer the questions, and get your score straight away.</p>
      <p class="hero-note">Free. No account needed. Nothing you enter leaves your device.</p>
    </div>
  </section>

  <section>
    <div class="wrap">
      <div class="section-head">
        <p class="eyebrow">Choose a score</p>
        <h2>Published knee scores</h2>
        <p>Not sure where to start? The main <a href="../index.html#quiz">My Knee Score test</a> is the quickest check. Use these when a clinician asks for a specific score, or when you want more detail on one area.</p>
      </div>
      <div class="filters" role="group" aria-label="Filter by category">
        <button type="button" class="chip is-on" data-filter="all" aria-pressed="true">All</button>
        ${cats.map(c => `<button type="button" class="chip" data-filter="${esc(c)}" aria-pressed="false">${esc(c)}</button>`).join("\n        ")}
      </div>
      <div class="score-grid" id="scoreGrid">
        ${published.map(card).join("\n        ")}
      </div>
    </div>
  </section>

  <section class="paper">
    <div class="wrap">
      <div class="section-head">
        <p class="eyebrow">In development</p>
        <h2>My Knee Score tools</h2>
        <p>Short scores developed by My Knee Score. They have not yet been validated in published research, so treat the result as a guide.</p>
      </div>
      <div class="score-grid">
        ${own.map(card).join("\n        ")}
      </div>
      <p class="coming">Coming soon, once licence permission is in place: ${Object.values(EXCLUDED).map(esc).join(" and ")}.</p>
    </div>
  </section>
</main>
${disclaimer}
${footer}
<script src="assets/hub.js"></script>
</body>
</html>
`;
fs.writeFileSync(path.join(OUT, "index.html"), hub);

// ---------- per-score pages ----------
function list(items) {
  return items && items.length ? `<ul class="ticks">${items.map(i => `<li>${esc(i)}</li>`).join("")}</ul>` : "";
}

function sourceLink(s) {
  if (s.doi) return ` <a href="https://doi.org/${esc(s.doi)}" rel="noopener" target="_blank">Read the paper</a>`;
  if (s.pubmedId) return ` <a href="https://pubmed.ncbi.nlm.nih.gov/${esc(s.pubmedId)}/" rel="noopener" target="_blank">PubMed</a>`;
  return "";
}

function scorePage(s) {
  const n = s.mode === "quick" ? s.questionSet.length : s.questions;
  const start = s.mode === "quick"
    ? `<div class="hero-actions"><button type="button" class="btn btn-gold" data-open-quiz>Start the ${esc(s.acronym)}</button><a class="btn btn-ghost" href="index.html">All scores</a></div>`
    : `<div class="hero-actions"><a class="btn btn-gold" href="#tool">Start the ${esc(s.acronym)}</a><a class="btn btn-ghost" href="index.html">All scores</a></div>`;
  const warn = unvalidated(s)
    ? `<p class="warn-note">This score is ${esc(s.validationLevel.toLowerCase())}. Treat the result as a guide only.</p>` : "";

  const tool = s.mode === "quick" ? "" : `
  <section id="tool" class="tool-section">
    <div class="wrap">
      <div class="section-head">
        <p class="eyebrow">The questionnaire</p>
        <h2>Score your knee</h2>
        <p>Rate each item from 0 (worst) to the top of its scale (best). Your score updates as you go.</p>
      </div>
      <div id="toolApp" class="tool-app"></div>
    </div>
  </section>`;

  return `${head(`${s.acronym} | ${s.fullName} | My Knee Score`, `Take the ${s.fullName} (${s.acronym}) online. ${n} questions, ${s.completionTime}. Get your score instantly.`)}
<body data-score="${esc(s.slug)}">
${header(false)}
<main id="top">
  <section class="hero hero-slim">
    <div class="wrap">
      <p class="eyebrow"><a href="index.html">Advanced scores</a> &middot; ${esc(s.category)}</p>
      <h1>${esc(s.fullName)} <em>(${esc(s.acronym)})</em></h1>
      <p class="lede">${esc(s.description)}</p>
      <ul class="facts">
        <li><b>${n}</b> question${n === 1 ? "" : "s"}</li>
        <li><b>${esc(s.completionTime)}</b></li>
        <li>Score <b>${esc(rangeText(s))}</b></li>
        <li><b>${esc(s.validationLevel)}</b></li>
      </ul>
      ${warn}
      ${start}
    </div>
  </section>
${tool}
  <section class="about">
    <div class="wrap about-grid">
      <div>
        <h2>About the ${esc(s.acronym)}</h2>
        <h3>Who it is for</h3>
        <p>${esc(s.whoItsFor)}</p>
        <h3>What it measures</h3>
        <p>${esc(s.whatItMeasures)}</p>
        ${s.subscales && s.subscales.length ? `<h3>Sections</h3>${list(s.subscales)}` : ""}
        <h3>Reading your score</h3>
        <p>${esc(s.scoringInterpretation)}</p>
      </div>
      <aside class="side-card">
        <p class="eyebrow">Strengths</p>
        ${list(s.strengths)}
        <p class="eyebrow">Limitations</p>
        ${list(s.limitations)}
        <p class="eyebrow">Source</p>
        <p class="cite">${esc(s.citation)}${sourceLink(s)}</p>
        <p class="cite">Licence: ${esc(s.licenseType)}${s.licenseDetails ? `. ${esc(s.licenseDetails)}` : ""}</p>
      </aside>
    </div>
  </section>
</main>
${disclaimer}
${footer}
${s.mode === "quick" ? quizShell(s) : ""}
<script src="assets/scores-data.js"></script>
<script src="assets/engine.js"></script>
<script src="assets/app.js"></script>
</body>
</html>
`;
}

function quizShell(s) {
  return `<div class="quiz-app" id="quizApp" role="dialog" aria-modal="true" aria-label="${esc(s.acronym)} questionnaire" hidden>
  <div class="quiz-topbar">
    <div class="wrap quiz-topbar-inner">
      <button type="button" class="quiz-exit" id="quizExit" aria-label="Close the questionnaire">Exit</button>
      <div class="progress-track" aria-hidden="true"><div class="progress-fill" id="progressFill"></div></div>
      <p class="progress-meta" id="progressMeta" aria-live="polite"></p>
    </div>
  </div>
  <div class="q-stage">
    <div class="wrap narrow">
      <div id="quizBody"></div>
      <div class="q-nav" id="quizNav">
        <button type="button" class="btn btn-ghost-green" id="backBtn">Back</button>
        <button type="button" class="btn btn-green" id="nextBtn">Next</button>
      </div>
      <div class="result" id="result" aria-live="polite"></div>
    </div>
  </div>
</div>`;
}

// Remove pages for scores that are no longer published (e.g. newly excluded)
const keep = new Set(["index.html", ...scores.map(s => `${s.slug}.html`)]);
for (const f of fs.readdirSync(OUT)) {
  if (f.endsWith(".html") && !keep.has(f)) fs.unlinkSync(path.join(OUT, f));
}

for (const s of scores) {
  fs.writeFileSync(path.join(OUT, `${s.slug}.html`), scorePage(s));
}

console.log(`Built ${scores.length} score pages from kneescore-research@${commit}. Excluded: ${Object.keys(EXCLUDED).join(", ")}`);
